srcdir=/home/igarashi/cortina/build_dir/linux-g2_wan/libreswan-3.9/testing/pluto/
OBJDIR=OBJ.linux.arm
OBJDIRTOP=/home/igarashi/cortina/build_dir/linux-g2_wan/libreswan-3.9/OBJ.linux.arm
OSDEP=linux
BUILDENV=linux
VPATH+=${srcdir}
LIBRESWANSRCDIR=/home/igarashi/cortina/build_dir/linux-g2_wan/libreswan-3.9
include ${srcdir}Makefile
-include Makefile.depend
