/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/igarashi/cortina/build_dir/target-arm_uClibc-0.9.32_eabi/perl/perl-5.10.0/host-perl/miniperl ../bin/enc2xs -Q -o bi_00_t.c -f bi_00_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t big5_eten_encoding;
