/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/igarashi/cortina/build_dir/target-arm_uClibc-0.9.32_eabi/perl/perl-5.10.0/host-perl/miniperl bin/enc2xs -Q -O -o def_t.c -f def_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t ascii_encoding;
extern encode_t ascii_ctrl_encoding;
extern encode_t iso_8859_1_encoding;
extern encode_t null_encoding;
