#!/bin/sh
# **********************************************************#
# libupsclient-config: helper script for NUT libupsclient   #
# **********************************************************#
# Copyright 2003 - Arnaud Quette                            #
# Distributed under the GNU GPL v2                          #
# See the distribution lib/README for usage information     #
# **********************************************************#

Version="2.7.2"
prefix=/usr
exec_prefix=${prefix}
Libs="-L${exec_prefix}/lib -lupsclient -L/home/igarashi/cortina/staging_dir/target-arm_uClibc-0.9.32_eabi/usr//lib -lssl -lcrypto  "
Cflags="-I${prefix}/include -I/home/igarashi/cortina/staging_dir/target-arm_uClibc-0.9.32_eabi/usr//include  "

case "$1" in

  --cflags)
	echo "$Cflags"
	;;
  --libs)
	echo "$Libs"
	;;
  --version)
	echo $Version
	;;
  *)
	echo "Usage: libupsclient-config {--cflags|--libs|--version}"
	exit 1
esac

