srcdir=/home/igarashi/cortina/build_dir/linux-g2_wan/libreswan-3.9/testing/crypto/pk-dh-03/
OBJDIR=OBJ.linux.i386
OBJDIRTOP=/home/igarashi/cortina/build_dir/linux-g2_wan/libreswan-3.9/OBJ.linux.i386
OSDEP=linux
BUILDENV=linux
VPATH+=${srcdir}
LIBRESWANSRCDIR=/home/igarashi/cortina/build_dir/linux-g2_wan/libreswan-3.9
include ${srcdir}Makefile
-include Makefile.depend
