/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/igarashi/cortina/build_dir/target-arm_uClibc-0.9.32_eabi/perl/perl-5.10.0/host-perl/miniperl ../bin/enc2xs -Q -O -o symbol_t.c -f symbol_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t AdobeSymbol_encoding;
extern encode_t AdobeZdingbat_encoding;
extern encode_t MacDingbats_encoding;
extern encode_t MacSymbol_encoding;
extern encode_t dingbats_encoding;
extern encode_t symbol_encoding;
