/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/igarashi/cortina/build_dir/target-arm_uClibc-0.9.32_eabi/perl/perl-5.10.0/host-perl/miniperl ../bin/enc2xs -Q -o ma_04_t.c -f ma_04_t.fnm
 enc2xs VERSION 2.05
*/
extern encode_t MacKorean_encoding;
